### PR TITLE
Add instructions for IGV Desktop.

### PR DESCRIPTION
**Pull request by deflaux**
http://googlegenomics.readthedocs.org/en/staging/use_cases/browse_genomic_data/igv.html

### CODE REVIEW

**Comment by mbookman** [comment]
Fantastic. LGTM.

**Comment by deflaux** [comment]
@jrobinso The integration of [IGV](https://github.com/igvteam/igv) with Google Genomics and Google Cloud Storage is really cool!!!

Please let me know if you have any feedback on this cookbook update?  Its on our staging site for now so you can view it [here](http://googlegenomics.readthedocs.org/en/staging/use_cases/browse_genomic_data/igv.html).

**Comment by deflaux** [comment]
@jrobinso I'm going to merge this now but I'm happy to make changes at any point.  Thanks!

**Comment by jrobinso** [comment]
Thanks Nicole

**Pull request merged**
